language: php
php:
    - '7.1'
    - '7.2'
    - '7.3'

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
    - sudo apt-get update
    - sudo apt-get install -y tor

install:
    - travis_retry composer self-update && composer --version
    - travis_retry composer install --no-interaction

script:
    - composer validate --no-check-lock
    - vendor/bin/phpunit -c phpunit.xml --coverage-clover=coverage.clover

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
